### ISSUE TITLE
As a user I would like to view a detailed report of all expenses, income, and summary information

### ISSUE THREAD

**Issue by DamianGow** [DamianGow/Ewallet-SENG210#11]

**Comment by snaveknight** [comment]
//for the detailed report
	private static JPanel detailedSummaryPanel;
	private static JTextArea detailedSummaryTextArea = new JTextArea();
	private static JButton detailedSummaryHomeButton = new JButton();

	//detailed summary pane
	detailedSummaryPanel = new JPanel();
	detailedSummaryPanel.setBackground(Color.black);
	detailedSummaryPanel.setBounds(0, 0, 455, 600);
	detailedSummaryPanel.setLayout(null);
	detailedSummaryPanel.setVisible(false);
	
	detailedSummaryHomeButton = new JButton("Home");
	detailedSummaryHomeButton.setBounds(170, 30, 120, 70);
	detailedSummaryHomeButton.setFocusable(false);
	detailedSummaryHomeButton.addActionListener(this);
	detailedSummaryHomeButton.setVisible(true);
	
	detailedSummaryTextArea = new JTextArea();
	detailedSummaryTextArea.setBounds(30, 130, 395, 400); // Set the position and size of the text area
	detailedSummaryTextArea.setEditable(false); // Set the text area as non-editable

        this.add(detailedSummaryPanel);
        detailedSummaryPanel.add(detailedSummaryTextArea);
	detailedSummaryPanel.add(detailedSummaryHomeButton);

        			if(e.getSource()==detailedSummaryButton) {
				try {
					detailedSummaryTextArea.setText("");
					detailedSummaryOverviewWindow();
					List<Map<String, Object>> incomeAmount = Expenser.PrintIncomereport();
					 List<Map<String, Object>> expensesList = Expenser.PrintExpensereport();
				    
				    // Iterate over the expenses list and append details to the text area
				    for (Map<String, Object> incomeDetailsMap : incomeAmount) {
				        
				    	
				    if (typeSorter.getSelectedIndex()== 0) {	
				        if((String) incomeDetailsMap.get("Type") == "Primary") { 
				        String intype = (String) incomeDetailsMap.get("Type");
				        double inamount = (double) incomeDetailsMap.get("Income");
				        
				        // Append expense details to the text area
				        detailedSummaryTextArea.append("Income Type: " + intype+ "\n");
				        detailedSummaryTextArea.append("Income Amount: " + inamount + "\n");
				       
				        detailedSummaryTextArea.append("-------------------------------------------------\n");
				        }
				    }
				    else if (typeSorter.getSelectedIndex()== 1) {	
				        if((String) incomeDetailsMap.get("Type") == "Secondary") { 
				        String intype = (String) incomeDetailsMap.get("Type");
				        double inamount = (double) incomeDetailsMap.get("Income");
				        
				        // Append expense details to the text area
				        detailedSummaryTextArea.append("Income Type: " + intype+ "\n");
				        detailedSummaryTextArea.append("Income Amount: " + inamount + "\n");
				       
				        detailedSummaryTextArea.append("-------------------------------------------------\n");
				        }
				    }
				    else if (typeSorter.getSelectedIndex()== 2) {	
				        if((String) incomeDetailsMap.get("Type") == "Other") { 
				        String intype = (String) incomeDetailsMap.get("Type");
				        double inamount = (double) incomeDetailsMap.get("Income");
				        
				        // Append expense details to the text area
				        detailedSummaryTextArea.append("Income Type: " + intype+ "\n");
				        detailedSummaryTextArea.append("Income Amount: " + inamount + "\n");
				       
				        detailedSummaryTextArea.append("-------------------------------------------------\n");
				        }
				    }
				    else if (typeSorter.getSelectedIndex()== 3) {	
				       
				        String intype = (String) incomeDetailsMap.get("Type");
				        double inamount = (double) incomeDetailsMap.get("Income");
				        
				        // Append expense details to the text area
				        detailedSummaryTextArea.append("Income Type: " + intype+ "\n");
				        detailedSummaryTextArea.append("Income Amount: " + inamount + "\n");
				       
				        detailedSummaryTextArea.append("-------------------------------------------------\n");
				        }
				    }
					    
					    // Iterate over the expenses list and append details to the text area
					    for (Map<String, Object> expenseDetails : expensesList) {
					        String category = (String) expenseDetails.get("Category");
					        String subcategory = (String) expenseDetails.get("Subcategory");
					        double amount = (double) expenseDetails.get("Amount");
					        String frequency = (String) expenseDetails.get("Frequency");
					        
					        // Append expense details to the text area
					        detailedSummaryTextArea.append("Category: " + category + "\n");
					        detailedSummaryTextArea.append("Subcategory: " + subcategory + "\n");
					        detailedSummaryTextArea.append("Amount: " + amount + "\n");
					        detailedSummaryTextArea.append("Frequency: " + frequency + "\n"); 
					        
					        detailedSummaryTextArea.append("-------------------------------------------------\n");
					    }
				    
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

			if(e.getSource()==detailedSummaryHomeButton) {
				try {
					screenReset();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

		public static void screenReset() throws IOException {
			startPanel.setVisible(true);
			conPanel.setVisible(false);
			expensePanel.setVisible(false);
			incomePanel.setVisible(false);
			summaryOverviewPanel.setVisible(false);
			fullExpenseOverviewPanel.setVisible(false);
			fullIncomeOverviewPanel.setVisible(false);
			savePanel.setVisible(false);
			---->detailedSummaryPanel.setVisible(false);<-----
		}
		public static void detailedSummaryOverviewWindow() throws IOException{
			
			summaryOverviewPanel.setVisible(false);
			
			detailedSummaryPanel.setVisible(true);
		}
