### ISSUE TITLE
As a user I would like to load multiple expenses from an external file all at once returning true if loaded successfully and false otherwise

### ISSUE THREAD

**Issue by DamianGow** [DamianGow/Ewallet-SENG210#2]

**Comment by snaveknight** [comment]
public static void addExpensesFromFile(String fileName) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] expenseData = line.split(",");

                // Extract expense details from the line
                String category = expenseData[0].trim();
                String subcategory = expenseData[1].trim();
                double amount = Double.parseDouble(expenseData[2].trim());
                String frequency = expenseData[3].trim();

                // Call the addExpense function with the extracted details
                addExpense(category, subcategory, amount, frequency);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

^^^^^^^^^^^^^^^EXPENSER.JAVA^^^^^^^^^^^^^^^^^^^^^

	private static JButton importExpenseButton = new JButton();
	importExpenseButton = new JButton("Import expense");
	importExpenseButton.setBounds(170,110, 150, 70);
	importExpenseButton.setFocusable(false);
	importExpenseButton.addActionListener(this);
	importExpenseButton.setVisible(true);	

	expensePanel.add(importExpenseButton);

			if(e.getSource()==importExpenseButton) { //resets to home screen
				String fileName = "C:\\Users\\snave\\eclipse-workspace\\210Project-2021(2)\\src\\expenseImport.txt";
				Expenser.addExpensesFromFile(fileName);
				JOptionPane.showMessageDialog(null, "Expense added! Look in Console for details!", "Success", JOptionPane.INFORMATION_MESSAGE);
			}
